server:
  port: 2222
spring:
  application:
    name: compute-service1  # 注册到注册中心的服务名称
  cloud:
    config:
      discovery:
        enabled: true
        service-id: compute-server  # 注册中心的服务ID
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
