server:
  port: 3333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
spring:
  application:
    name: gateway-zuul
zuul:
  routes:
    compute-service1: /api-a/**  # 表示只要访问以/api-a/开头的多层目录都可以路由到 id为compute-service1的服务上
  #zuul.routes.api-a.path=/api-a/**
  #zuul.routes.api-a.serviceId=compute-service1